server:
  port: 8090
spring:
  application:
    name: shopapp
  datasource:
      url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: nJDco+uZAcHpF6BAk3PKl2Z5cxPCe7XhpKypZ60eurYkE9TPkYtJDuf4iYYz5DN8