server:
  port: 8088
spring:
  application:
    name: shopapp
  datasource:
      url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: g/7u3CvzbtD085pTKwZ67oPOkdAVs8ERgtff8bpc96Om6dTdEFdBjrNJJsbPiGTd